image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "29"
  ANDROID_BUILD_TOOLS: "28.0.3"
  ANDROID_SDK_TOOLS:   "4333796"

stages:
- build
- test

lintDebug:
  stage: build
  script:
  - ./gradlew lint

buildDebug:
  stage: build
  script:
  - ./gradlew build
  artifacts:
    paths:
    - ./Branch-SDK/build/outputs/aar/

debugTests:
  stage: test
  script:
  - ./gradlew test

emulatorTests:
  stage: test
  script:
  - python2 deploy/build_test.py
